package com.example.sudoku2.controller;

import com.example.sudoku2.model.user.User;
import com.example.sudoku2.view.SudokuGameStage;
import com.example.sudoku2.view.SudokuHelpStage;
import com.example.sudoku2.view.SudokuWelcomeStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.TextField;

import java.io.IOException;


/**
 * Controller class for the welcome screen of the Sudoku application.
 * <p>
 * This controller manages the main menu interactions, including starting a new game,
 * opening the help window, and exiting the application.
 */
public class SudokuWelcomeController {

    /** Text field for entering the user's nickname. */
    @FXML
    private TextField nicknameTxt;

    /**
     * Handles the action of starting the game.
     * <p>
     * If a nickname is entered, this method creates a new {@link User},
     * passes it to the {@link SudokuGameStage} controller, and then
     * closes the current welcome stage.
     *
     * @param event the {@link ActionEvent} generated by clicking the "Play" button.
     */
    @FXML
    void handlePlay(ActionEvent event) {
        String nickname = nicknameTxt.getText().trim();
        try {
            if (!nickname.equals("")) {
                SudokuGameStage.getInstance().getController().setUser(new User(nickname));
                SudokuWelcomeStage.deleteInstance();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * Handles the action of exiting the application.
     * <p>
     * When triggered, this method closes the {@link SudokuWelcomeStage}.
     *
     * @param event the {@link ActionEvent} generated by clicking the "Leave" button.
     */
    @FXML
    void handleLeave(ActionEvent event) {
        SudokuWelcomeStage.deleteInstance();
    }

    /**
     * Handles the action of opening the help screen.
     * <p>
     * When triggered, this method opens the {@link SudokuHelpStage}
     * and closes the current {@link SudokuWelcomeStage}.
     *
     * @param event the {@link ActionEvent} generated by clicking the "Help" button.
     */
    @FXML
    void handleHelp(ActionEvent event) {
        try {
            SudokuHelpStage.getInstance();
            SudokuWelcomeStage.deleteInstance();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
