package com.example.sudoku2.controller;

import com.example.sudoku2.view.SudokuFinalStage;
import com.example.sudoku2.view.SudokuWelcomeStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import java.io.IOException;

/**
 * Controller class for the final screen of the Sudoku application.
 * <p>
 * This controller manages user interactions on the "Final" stage,
 * such as returning to the main menu after the game ends.
 */
public class SudokuFinalController {

    /**
     * Handles the action of returning to the main menu.
     * <p>
     * When triggered, this method opens the {@link SudokuWelcomeStage}
     * and closes the current {@link SudokuFinalStage}.
     *
     * @param event the {@link ActionEvent} generated by the menu button click.
     */
    @FXML
    void handleMenu(ActionEvent event) {
        try {
            SudokuWelcomeStage.getInstance();
            SudokuFinalStage.deleteInstance();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
