package com.example.sudoku2.controller;

import com.example.sudoku2.view.SudokuHelpStage;
import com.example.sudoku2.view.SudokuWelcomeStage;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import java.io.IOException;

/**
 * Controller class for the help screen of the Sudoku application.
 * <p>
 * This controller manages user interactions within the help window,
 * such as navigating back to the main menu.
 */
public class SudokuHelpController {

    /**
     * Handles the action of returning to the main menu.
     * <p>
     * When triggered, this method opens the {@link SudokuWelcomeStage}
     * and closes the current {@link SudokuHelpStage}.
     *
     * @param event the {@link ActionEvent} generated by the "Back" button click.
     */
    @FXML
    void handleBack(ActionEvent event){
        try {
            SudokuWelcomeStage.getInstance();
            SudokuHelpStage.deleteInstance();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
